[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.19"
optimizer = true
optimizer_runs = 200
gas_limit = 9223372036854775807
gas_price = 3000000000

[rpc_endpoints]
memecore_testnet = "https://rpc.formicarium.memecore.net"

[etherscan]
memecore_testnet = { key = "${MEMECORE_API_KEY}", url = "https://formicarium.memecorescan.io/api/" }